### ISSUE TITLE
UWP 10.0 support

### ISSUE THREAD

**Issue by jrjrguo** [nunit/nunit.xamarin#110]
Hello,

Since we are bringing back netstandard1.4 support in the next NUnit release, is it possible to have it supported in NUnit.Xamarin as well? We are looking to switch to nunit.xamarin for our uwp testing, so just wondering how much work would there be to bring back uap10.0 support? Thanks.

**Comment by samsnowy** [comment]
On the topic of UWP 10.0 support, I have a repro here that is using Nunit.Xamarin 3.6.1 and failing at the 
global::Xamarin.Forms.Forms.Init(e) call.

The difference between this repro and the one in the uap demo is that I've defined my own entry point and I don't have any ".xaml" files:
[TestUWP.zip](https://github.com/nunit/nunit.xamarin/files/2178380/TestUWP.zip)

We fail with an exception:    

at Windows.UI.Xaml.ResourceDictionary.put_Source(Uri value)
at Xamarin.Forms.Forms.GetTabletResources()
at Xamarin.Forms.Forms.Init(IActivatedEventArgs launchActivatedEventArgs, IEnumerable1 rendererAssemblies) 
at IDR.RTD.App.OnLaunched(LaunchActivatedEventArgs e) 

Error HRESULT E_FAIL has been returned from a call to a COM component. 

It seems like it's not able to get "resources.xbf" if you don't use and generate the xaml stuff through a ".xaml' file.
